"""empty message

Revision ID: 11a6ee102ec5
Revises: db0902393edd
Create Date: 2023-12-13 23:32:56.725088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a6ee102ec5'
down_revision = 'db0902393edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('api_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('api_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
